# Generated by Django 4.2.5 on 2023-09-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
