# Generated by Django 4.2.5 on 2023-09-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0003_objectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='objectives',
        ),
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.ManyToManyField(related_name='course', to='UserView.objectives'),
        ),
    ]
