# Generated by Django 4.2.5 on 2023-09-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0004_remove_course_objectives_course_objectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='requirements',
        ),
        migrations.AddField(
            model_name='course',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
