# Generated by Django 4.2.5 on 2023-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0006_course_description_ar_course_level_ar_course_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90)),
                ('description', models.CharField(default='', max_length=400)),
                ('description_ar', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.ManyToManyField(related_name='Requirements', to='UserView.requirements'),
        ),
    ]
