# Generated by Django 4.2.5 on 2023-09-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0007_requirements_course_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='after',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='after_ar',
            field=models.TextField(default=''),
        ),
    ]
