# Generated by Django 4.2.5 on 2023-09-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0008_course_after_course_after_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_ar',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
    ]
