# Generated by Django 4.2.5 on 2023-10-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0009_course_duration_ar_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='price_ar',
            field=models.CharField(default='', max_length=200),
        ),
    ]
